apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s
  labels:
    app: app-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-k8s
  template:
    metadata:
      labels:
        app: app-k8s
    spec:
      containers:
        - name: app-k8s
          image: snic/k8s-app
         