apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-clone-new
  labels:
    app: whoami-clone-new
  namespace: dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-clone-new
  template:
    metadata:
      labels:
        app: whoami-clone-new
    spec:
      containers:
        - name: whoami-clone-new
          image: gianluca1606/whoami-clone:new