apiVersion: v1
kind: Service
metadata:
  name: whoami-clone-new
  namespace: dev  
spec:
  selector:
    app: whoami-clone-new
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30012
