version: '3.1'
services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ibimsuser
      WORDPRESS_DB_PASSWORD: ibimspassword
      WORDPRESS_DB_NAME: ibimsdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ibimsdb
      MYSQL_USER: ibimsuser
      MYSQL_PASSWORD: ibimspassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: