apiVersion: v1
kind: Service
metadata:
  name: k8s-app-service
  namespace: dev  
spec:
  selector:
    app: k8s-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
