apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
  namespace: dev  
spec:
  securityContext:
      runAsUser: 0
  containers:
    - name: redis
      image: redis
      volumeMounts:
      - mountPath: /data
        name: redis-data
  volumes:
  - name: redis-data
    hostPath:
      path: /storage/redis
      type: Directory