apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  labels:
    app: k8s-app
  namespace: volumes  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app 
    spec:
      containers:
        - name: k8s-app
          image: snic/k8s-app
         
         