apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
  namespace: volumes
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-voll
     