apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: volumes
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi