apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-clone-consume
  labels:
    app: whoami-clone-consume
  namespace: dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-clone-consume
  template:
    metadata:
      labels:
        app: whoami-clone-consume
    spec:
      containers:
        - name: whoami-clone
          image: gianluca1606/whoami-clone:consume
          imagePullPolicy: Always
          env:
          - name: HOSTNAME
            value: "whoami-clone"