apiVersion: v1
kind: Service
metadata:
  name: app-k8s-service
  namespace: dev
spec:
  selector:
    app: app-k8s
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
