apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: configmaps
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi